In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("california_master_dataset_1111.csv")
df.head(5)

,zpid,palsId,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,price,...,plid,isCdpResult,style,isComingSoonCommunity,buildingName,isPropertyResultCDP,hdpData.homeInfo.group_type,hdpData.homeInfo.priceSuffix,info3String,info2String
0,2.073568e+09,17327010_26844339,ForSale,For Sale by Agent,https://photos.zillowstatic.com/fp/baa91158903...,True,/homedetails/8721-W-Sunset-Plaza-Ter-West-Holl...,FOR_SALE,House for sale,"$4,980,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.987515e+07,31493001_226002630,ForSale,For Sale by Agent,https://photos.zillowstatic.com/fp/60873898547...,True,/homedetails/23649-Aetna-St-Woodland-Hills-CA-...,FOR_SALE,House for sale,"$1,215,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.053261e+07,17327010_26846711,ForSale,For Sale by Agent,https://photos.zillowstatic.com/fp/8d2b3e54fc2...,True,/homedetails/2350-Benedict-Canyon-Dr-Beverly-H...,FOR_SALE,House for sale,"$2,629,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,https://photos.zillowstatic.com/fp/07b915b7231...,True,/b/645-w-9th-st-los-angeles-ca-CkBBCq/,FOR_SALE,For Rent,"From $389,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.093480e+07,17327006_26843895,ForSale,For Sale by Agent,https://photos.zillowstatic.com/fp/f95fee73996...,True,/homedetails/1161-W-67th-St-Los-Angeles-CA-900...,FOR_SALE,Multi-family home for sale,"$400,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def add_one(x):
    """
    Trả về x + 1.
    Hỗ trợ số (int/float/np.number), numpy array, pandas Series hoặc DataFrame.
    """
    try:
        return x + 1
    except Exception as e:
        raise TypeError(f"Không thể cộng 1 cho đối tượng loại {type(x)}: {e}")

In [4]:
df.shape

(5757, 112)

In [5]:
usefull_cols = [
    'zpid',
    'hdpData.homeInfo.price', 
    'statusText', 
    'hdpData.homeInfo.homeType',
    'hdpData.homeInfo.city',
    'hdpData.homeInfo.state', 
    'hdpData.homeInfo.latitude', 
    'hdpData.homeInfo.longitude',
    'baths', 
    'beds', 
    'area',
    'hdpData.homeInfo.lotAreaValue', 
    'hdpData.homeInfo.lotAreaUnit',
    'timeOnZillow'
]

df = df[usefull_cols]

In [6]:
df.rename(columns={
    'hdpData.homeInfo.price': 'price',
    'statusText': 'status',
    'hdpData.homeInfo.homeType': 'type',
    'hdpData.homeInfo.city': 'city',
    'hdpData.homeInfo.state': 'state',
    'hdpData.homeInfo.latitude': 'latitude',
    'hdpData.homeInfo.longitude': 'longitude',
    'baths': 'bathrooms',
    'beds': 'bedrooms',
    'area': 'living_area',
    'hdpData.homeInfo.lotAreaValue': 'lot_area',
    'hdpData.homeInfo.lotAreaUnit': 'lot_area_unit',
    'timeOnZillow': 'days_on_zillow'
}, inplace=True)

In [19]:
print(df.isnull().sum())

zpid                 0
price                0
status               0
type                 0
city                 0
state                0
latitude             0
longitude            0
bathrooms          964
bedrooms          1049
living_area       1041
lot_area           556
lot_area_unit      556
days_on_zillow       0
dtype: int64

In [20]:
# CÓ 58 NHÀ DIỆN TÍCH BẰNG 0 , ĐỔI RA NAN RỒI FILL MEDIAN
print((df['lot_area'] == 0).sum())

58
0

In [18]:
mask = df['lot_area'] < 20

df.loc[mask, 'lot_area'] *= 43560

In [8]:
df = df.dropna(subset=["zpid"])

In [23]:
df.head(5)

,zpid,price,status,type,city,state,latitude,longitude,bathrooms,bedrooms,living_area,lot_area,lot_area_unit,days_on_zillow
0,2.073568e+09,4980000.0,House for sale,SINGLE_FAMILY,West Hollywood,CA,34.100803,-118.380570,5.0,4.0,4126.0,4922.000,sqft,7.908150e+08
1,1.987515e+07,1215000.0,House for sale,SINGLE_FAMILY,Woodland Hills,CA,34.180298,-118.642500,2.0,3.0,1825.0,7840.800,sqft,1.020029e+09
2,2.053261e+07,2629000.0,House for sale,SINGLE_FAMILY,Beverly Hills,CA,34.112854,-118.433876,4.0,4.0,3019.0,43381.404,acres,4.203270e+08
4,2.093480e+07,400000.0,Multi-family home for sale,MULTI_FAMILY,Los Angeles,CA,33.978700,-118.295680,2.0,3.0,944.0,4268.880,sqft,9.995380e+08
5,2.131354e+07,849000.0,House for sale,SINGLE_FAMILY,San Pedro,CA,33.713604,-118.291880,2.0,2.0,1154.0,5002.000,sqft,6.436090e+08

In [26]:
# Xử lý null bằng cách fill  vào bằng median
df["bedrooms"] = df["bedrooms"].fillna(
    df["bedrooms"].median()
)

df["bathrooms"] = df["bathrooms"].fillna(
    df["bathrooms"].median()
)

In [24]:
print(df['lot_area'].min())
print(df['lot_area'].max())

0.0
870764.3999999999

In [31]:
print(df.isnull().sum())

zpid                 0
price                0
status               0
type                 0
city                 0
state                0
latitude             0
longitude            0
bathrooms            0
bedrooms             0
living_area       1168
lot_area           614
lot_area_unit      556
days_on_zillow       0
dtype: int64

In [30]:
print((df["living_area"] == 0).sum())

print((df["lot_area"] == 0).sum())

0
0

In [29]:
df["living_area"] = df["living_area"].replace(0, np.nan)
df["lot_area"] = df["lot_area"].replace(0, np.nan)

In [32]:
print(df.isnull().sum())

zpid                 0
price                0
status               0
type                 0
city                 0
state                0
latitude             0
longitude            0
bathrooms            0
bedrooms             0
living_area       1168
lot_area           614
lot_area_unit      556
days_on_zillow       0
dtype: int64

In [33]:
df["living_area"] = df["living_area"].fillna(
    df["living_area"].median()
)

df["lot_area"] = df["lot_area"].fillna(
    df["lot_area"].median()
)

In [36]:
print(df.isnull().sum())

zpid              0
price             0
status            0
type              0
city              0
state             0
latitude          0
longitude         0
bathrooms         0
bedrooms          0
living_area       0
lot_area          0
days_on_zillow    0
dtype: int64

In [35]:
df.drop(columns=["lot_area_unit"], inplace=True)

In [37]:
df["lot_area"].sort_values()

4016        20.00
4819        20.00
4516        20.00
4953        20.00
5280        20.01
          ...
5008    851162.40
3962    857696.40
4216    865667.88
4971    870328.80
4084    870764.40
Name: lot_area, Length: 5756, dtype: float64